name: Refresh Vaccination Database 

on:
  schedule:
    - cron: "0 3 * * 1"   # Every Monday at 03:00 UTC
  workflow_dispatch:       # Allow manual trigger in the Actions tab

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL pipeline
        run: |
          python etl_pipeline.py

      # Upload generated artifacts for download
      - name: Upload SQLite DB and outputs
        uses: actions/upload-artifact@v4
        with:
          name: vaccination-artifacts
          path: |
            vaccination.db
            clean_*.csv
            plot_*.png
